### ISSUE TITLE
Mardown not work correctly

### ISSUE THREAD

**Issue by ghost** [geschke/grav-theme-tikva#11]
Hi,

Again me :)

When i do 

``` bash
example bash markdown
multipleline1
multipleline2
```

I don't see the text, and the square

My question is, Is this styling Markdown is completely supported with this theme ?

edit : when I change theme, I can see the text, but not the square.

**Comment by geschke** [comment]
Hello!

I'm sorry, but I do not really understand, what you mean. 

If you have a look at https://learn.getgrav.org/content/markdown - I guess you want to use the syntax highlighting with "Github Flavoured Markdown", test it by copying the JavaScript example. If I do so, the output is as expected. (You need the highlighting plugin to work.)

If it does not work, please provide the complete markdown code of your text in a copy&pasteable format, so that I can just take it and test in my systems. 

Thanks & Kind regards,
   Ralf

**Comment by ghost** [comment]
Thank you for the informations !
