### ISSUE TITLE
suggest add bulmaswatch themes

### ISSUE THREAD

**Issue by ghost** [geschke/grav-theme-tikva#18]
Hi,

A suggestion for this theme Tikva is to add these themes : https://github.com/jenil/bulmaswatch.

That would be great if you can, these themes are for Bulma CSS, inspired by Bootswatch.

:)

**Comment by geschke** [comment]
Hello!

I don't know if I understand you right. Tikva supports all themes from Bootswatch (based on Bootstrap 4), you can choose between the original Bootswatch themes and a handful of my additions. 
Bulma CSS seems to be another CSS framework. Without any rating, there are hundreds of CSS frameworks available. It was one of the first decisions that Tikva should be based on Bootstrap 4. So  for me it's no option to switch the CSS framework, because I'm missing a reason for that.

Kind regards,
   Ralf

**Comment by ghost** [comment]
Ok, I understand no problem ! thanks
