### ISSUE TITLE
Blockquotes not working

### ISSUE THREAD

**Issue by SoDimicom** [geschke/grav-theme-tikva#8]
When i do a Blockquotes in a new page with > or "<\blockquote>", it doesn't work, you know why ?
I can't also put this for example
`<pre><code class="language-markdown">&gt; Donec massa lacus, ultricies a ullamcorper in, fermentum sed augue.
Nunc augue augue, aliquam non hendrerit ac, commodo vel nisi.
&gt;&gt; Sed adipiscing elit vitae augue consectetur a gravida nunc vehicula. Donec auctor
odio non est accumsan facilisis. Aliquam id turpis in dolor tincidunt mollis ac eu diam.</code></pre>`

<a href="http://www.bild.me" target="_blank"><img src="http://s1.bild.me/bilder/240416/9988760Capture.PNG" title="Bilder und Fotos hochladen - kostenlos!"></a>

i can view a good result in the peview of grav, but then on the website i view only text

However that's work on the default theme  Antimatter

**Comment by geschke** [comment]
I will test this later, thanks for your report!

Kind regards,
     Ralf

**Comment by SoDimicom** [comment]
Thanks ! Keep me informed

**Comment by geschke** [comment]
I can confirm the behavior you described. It's because of the underlying CSS framework. In the documentation of Bootstrap 4 the \<blockquote\> is written as "\<blockquote class="blockquote"\>. But this helps only if you're using the tags, not the markdown shortcuts. 
So a possible solution could be to add some CSS code to the custom stylesheet. But this has the disadvantage that it doesn't support the Bootswatch themes, i.e. the color of the vertical bar would be identically in all themes. That's not really nice... So I think it's better to add the styles to the source code of Bootswatch and regenerate the CSS files, but this needs more effort. Or the render process has to be modified... I will think about it. :-) 

Thanks for your patience. 
Kind regards,
   Ralf

**Comment by SoDimicom** [comment]
if it will be work with `<blockquote class="blockquote">` no problem, i'm going to test and say you

**Comment by SoDimicom** [comment]
Good it's works, but If a test 
`<div class="bd-example"><pre>
.example-element {
  margin-bottom: 1rem;
}
</pre></div>`

I am supposed to have :

![capture](https://cloud.githubusercontent.com/assets/7480045/23765619/0d86a50e-0502-11e7-8cfc-8d0273236b2f.PNG)


But I have this : 

![capture2](https://cloud.githubusercontent.com/assets/7480045/23765694/4abc1c2e-0502-11e7-8859-393ba735b9da.PNG)

I don't have the square that surrounds it.

**Comment by geschke** [comment]
Thanks for your comment. But let me ask - why did you expect the square that surrounds the code block? If you're looking at the Bootstrap documentation (https://v4-alpha.getbootstrap.com/content/code/) there is a square, but this is part of another additional CSS file (docs.min.css), so it's not part of the standard Bootstrap CSS. The class "bd-example" is also nowhere defined, it's also part of the the additional CSS file which is used on the Bootstrap documentation site. 
If you want additional CSS, you can add it by modifying the template files, or maybe there is a plugin to do this in a simpler way. 

For sure, I will fix the "blockquote" issue soon, so it will be available in the next version. 

Kind regards,
   Ralf
